scara_right_controllers:
  joint_1_controller:
    type: position_controllers/JointPositionController
    joint: scara_right_joint_1
    pid:
      p: 10.0
      i: 0.5
      d: 1.0
  
  joint_2_controller:
    type: position_controllers/JointPositionController
    joint: scara_right_joint_2
    pid:
      p: 10.0
      i: 0.5
      d: 1.0
  
  gripper_controller:
    type: position_controllers/JointPositionController
    joint: scara_right_gripper_left_joint
    pid:
      p: 5.0
      i: 0.1
      d: 0.5

# PD Controller Parameters
pd_controller:
  kp: [15.0, 15.0]  # Proportional gains
  kd: [2.0, 2.0]    # Derivative gains
  max_torque: [100.0, 100.0]  # Maximum torque
  max_velocity: [2.0, 2.0]    # Maximum velocity
